# Generated by Django 5.1.4 on 2025-01-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskAssignDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
